services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image:  mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
